---

version: "3.7"

services:
  tomcat:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.tomcat
    ports:
      - 8080:8080
    volumes:
      - ./my_tomcat/webapps/hello:/usr/local/tomcat/webapps/hello
      - ./my_tomcat/webapps/conf/Catalina/localhost:/usr/local/tomcat/webapps/conf/Catalina/localhost

  gradle-tomcat:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gradle
    ports:
      - 8080:8080
    volumes:
      - ./:/app
