---

version: "3.7"

services:
  app:
    #working_dir: /app
    #image: gradle:5.4.1-jdk8
    #image: tomcat:9.0.20-jdk8-slim
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.tomcat
    ports:
      - 8983:8983
      - 8080:8080
    volumes:
      - ./:/app
      #- ./solr_home:/opt/solr/server/solr
